"""Generate PDF reports using ReportLab."""
from __future__ import annotations

import io
import base64
from typing import List, Dict, Optional
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, PageBreak
from datetime import datetime


def generate_report_pdf(alerts: List[Dict], filename: Optional[str] = None) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.5*inch, bottomMargin=0.5*inch)
    styles = getSampleStyleSheet()
    story = []

    # Title
    title = Paragraph("Violence Detection Report", styles["Title"])
    story.append(title)
    story.append(Spacer(1, 8))
    
    # Generate date
    gen_date = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
    story.append(Paragraph(f"Generated: {gen_date}", styles["Normal"]))
    story.append(Spacer(1, 12))

    # Summary statistics
    total = len(alerts)
    critical = sum(1 for a in alerts if a.get("confidence", 0) >= 0.9)
    high = sum(1 for a in alerts if 0.8 <= a.get("confidence", 0) < 0.9)
    avg_conf = sum(a.get("confidence", 0) for a in alerts) / (total or 1)

    story.append(Paragraph("<b>Summary</b>", styles["Heading2"]))
    story.append(Paragraph(f"Total Events: {total}", styles["Normal"]))
    story.append(Paragraph(f"Critical (≥90%): {critical}", styles["Normal"]))
    story.append(Paragraph(f"High (80-90%): {high}", styles["Normal"]))
    story.append(Paragraph(f"Average Confidence: {avg_conf*100:.1f}%", styles["Normal"]))
    story.append(Spacer(1, 12))

    # Details table
    story.append(Paragraph("<b>Detection Details</b>", styles["Heading2"]))
    
    data = [["#", "Timestamp", "Camera/Source", "Confidence", "Label"]]
    for i, a in enumerate(alerts[:20], 1):  # Limit to first 20 alerts per page
        conf_pct = f"{a.get('confidence', 0)*100:.1f}%"
        data.append([
            str(i),
            a.get("timestamp", "N/A")[:19],  # Truncate to date/time
            a.get("camera", "unknown"),
            conf_pct,
            a.get("label", "violence")
        ])

    table = Table(data, colWidths=[0.5*inch, 1.5*inch, 1.5*inch, 1*inch, 1*inch])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.grey),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, 0), 10),
                ("BOTTOMPADDING", (0, 0), (-1, 0), 12),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.lightgrey]),
            ]
        )
    )
    story.append(table)
    story.append(Spacer(1, 12))

    # Add top 5 highest confidence alerts with images
    if alerts:
        story.append(PageBreak())
        story.append(Paragraph("<b>Top Detections (with Images)</b>", styles["Heading2"]))
        story.append(Spacer(1, 12))
        
        top_alerts = sorted(alerts, key=lambda a: a.get("confidence", 0), reverse=True)[:5]
        
        for idx, alert in enumerate(top_alerts, 1):
            story.append(Paragraph(f"Detection #{idx}: {alert.get('camera', 'unknown')}", styles["Heading3"]))
            story.append(Paragraph(f"Timestamp: {alert.get('timestamp', 'N/A')}", styles["Normal"]))
            story.append(Paragraph(f"Confidence: {alert.get('confidence', 0)*100:.1f}%", styles["Normal"]))
            story.append(Paragraph(f"Source: {alert.get('camera', 'unknown')} (Label: {alert.get('label', 'violence')})", styles["Normal"]))
            
            # Add image if available
            img_base64 = alert.get("image_base64")
            if img_base64:
                try:
                    img_data = base64.b64decode(img_base64)
                    img_buffer = io.BytesIO(img_data)
                    img = Image(img_buffer, width=3.5*inch, height=2.6*inch)
                    story.append(img)
                except Exception as e:
                    story.append(Paragraph(f"<i>Image unavailable: {str(e)}</i>", styles["Normal"]))
            
            story.append(Spacer(1, 12))

    story.append(Spacer(1, 12))
    story.append(Paragraph("Generated by Violence Detection System v1.0", styles["Normal"]))

    doc.build(story)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
